// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TranslationManager.API.Data;

#nullable disable

namespace TranslationManager.API.Migrations
{
    [DbContext(typeof(TranslationDbContext))]
    [Migration("20251004164444_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TranslationManager.API.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("De")
                        .HasColumnType("text")
                        .HasColumnName("de");

                    b.Property<string>("En")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("en");

                    b.Property<bool>("MobileSynced")
                        .HasColumnType("boolean")
                        .HasColumnName("mobile_synced");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("resource_key");

                    b.Property<string>("Tr")
                        .HasColumnType("text")
                        .HasColumnName("tr");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Platform");

                    b.HasIndex("ResourceKey")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("translations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            De = "Willkommen in unserer Anwendung!",
                            En = "Welcome to our application!",
                            MobileSynced = false,
                            Platform = "Backend",
                            ResourceKey = "welcome.message",
                            Tr = "Uygulamamıza hoş geldiniz!",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            De = "Anmelden",
                            En = "Login",
                            MobileSynced = false,
                            Platform = "Backend",
                            ResourceKey = "login.title",
                            Tr = "Giriş",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            De = "Dashboard",
                            En = "Dashboard",
                            MobileSynced = false,
                            Platform = "Backend",
                            ResourceKey = "dashboard.title",
                            Tr = "Kontrol Paneli",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            De = "Speichern",
                            En = "Save",
                            MobileSynced = true,
                            Platform = "Android/iOS",
                            ResourceKey = "button.save",
                            Tr = "Kaydet",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            De = "Abbrechen",
                            En = "Cancel",
                            MobileSynced = true,
                            Platform = "Android/iOS",
                            ResourceKey = "button.cancel",
                            Tr = "İptal",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
